# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='display',
            field=models.BooleanField(default=True),
        ),
    ]
