# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-26 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
